stages:
  - build
  - test
  - docs

variables:
  IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
  BATCH_BUILD: "1"
  V: "0"
  GIT_SUBMODULE_STRATEGY: "recursive"
  MAKEFLAGS: "-j5 --no-keep-going"

before_script:
  - export PATH=${PATH}:/esppool
  # add gitlab ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_script:
  - esppool -r all

.setup_idf_v4_3: &setup_idf_v4_3
  # Cloning esp-idf
  - echo Cloning esp-idf - Started
  - git clone --recursive --branch release/v4.3 --depth 1 https://github.com/espressif/esp-idf.git
  - pushd esp-idf
  - echo Cloning esp-idf - Done
  # Running install.sh
  - echo Running install.sh - Started
  - ./install.sh
  - echo Running install.sh - Done
  # Running export.sh
  - echo Running export.sh - Started
  - . export.sh
  - echo Running export.sh - Done
  # Applying patch for v4.3
  - git apply -v $CI_PROJECT_DIR/idf-patches/privilege-separation_support_v4.3.3.patch
  - popd

.setup_idf_v4_4: &setup_idf_v4_4
  # Cloning esp-idf
  - echo Cloning esp-idf - Started
  - git clone --recursive --branch v4.4.3 --depth 1 https://github.com/espressif/esp-idf.git
  - pushd esp-idf
  - echo Cloning esp-idf - Done
  # Running install.sh
  - echo Running install.sh - Started
  - ./install.sh
  - echo Running install.sh - Done
  # Running export.sh
  - echo Running export.sh - Started
  - . export.sh
  - echo Running export.sh - Done
  # Applying patch for v4.4
  - git apply -v $CI_PROJECT_DIR/idf-patches/privilege-separation_support_v4.4.3.patch
  - popd

.build_examples: &build_examples
  # Build blink
  - pushd $CI_PROJECT_DIR/examples/blink
  - idf.py set-target $TARGET_NAME
  - idf.py build
  - popd
  # Build http_request
  - pushd $CI_PROJECT_DIR/examples/http_request
  - idf.py set-target $TARGET_NAME
  - idf.py build
  - popd
  # Build https_request
  - pushd $CI_PROJECT_DIR/examples/https_request
  - idf.py set-target $TARGET_NAME
  - idf.py build
  - popd
  # Build esp_http_client
  - pushd $CI_PROJECT_DIR/examples/esp_http_client
  - idf.py set-target $TARGET_NAME
  - idf.py build
  - popd
  # Build esp_user_ota
  - pushd $CI_PROJECT_DIR/examples/esp_user_ota
  - idf.py set-target $TARGET_NAME
  - idf.py build
  - popd

.build_examples_v4.3:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env:priv-sep
  tags:
    - build_esppool

  artifacts:
    paths:
      - ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.3.tar.gz
    expire_in: 2 days
    when: always

  script:
    - *setup_idf_v4_3
    - *build_examples

.build_examples_v4.4:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env:priv-sep
  tags:
    - build_esppool

  artifacts:
    paths:
      - ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.4.tar.gz
    expire_in: 2 days
    when: always

  script:
    - *setup_idf_v4_4
    - *build_examples

esp32c3_build_examples_v4.3:
  extends: .build_examples_v4.3
  variables:
    TARGET_NAME: "esp32c3"

esp32c3_build_examples_v4.4:
  extends: .build_examples_v4.4
  variables:
    TARGET_NAME: "esp32c3"

esp32s3_build_examples_v4.4:
  extends: .build_examples_v4.4
  variables:
    TARGET_NAME: "esp32s3"

.build_tests_v4.3:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env:priv-sep
  tags:
    - build_esppool

  artifacts:
    paths:
     - ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.3.tar.gz
    expire_in: 2 days
    when: always

  script:
    - *setup_idf_v4_3
    # Build violation_test
    - pushd $CI_PROJECT_DIR/tests/violation_test
    - idf.py set-target $TARGET_NAME
    - idf.py build
    - tar -czvf ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.3.tar.gz build/bootloader/bootloader.bin build/partition_table/partition-table.bin build/violation_test.bin build/user_app/user_app.bin
    - mv ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.3.tar.gz $CI_PROJECT_DIR/
    - popd

.build_tests_v4.4:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env:priv-sep
  tags:
    - build_esppool

  artifacts:
    paths:
     - ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.4.tar.gz
    expire_in: 2 days
    when: always

  script:
    - *setup_idf_v4_4
    # Build violation_test
    - pushd $CI_PROJECT_DIR/tests/violation_test
    - idf.py set-target $TARGET_NAME
    - idf.py build
    - tar -czvf ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.4.tar.gz build/bootloader/bootloader.bin build/partition_table/partition-table.bin build/violation_test.bin build/user_app/user_app.bin
    - mv ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.4.tar.gz $CI_PROJECT_DIR/
    - popd

esp32c3_build_tests_v4.3:
  extends: .build_tests_v4.3
  variables:
    TARGET_NAME: "esp32c3"

esp32c3_build_tests_v4.4:
  extends: .build_tests_v4.4
  variables:
    TARGET_NAME: "esp32c3"

esp32s3_build_tests_v4.4:
  extends: .build_tests_v4.4
  variables:
    TARGET_NAME: "esp32s3"

.run_tests_v4.3:
  stage: test
  image: $CI_DOCKER_REGISTRY/esp32-ci-env:priv-sep
  tags:
    - test_esppool
  script:
    - tar -xzf ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.3.tar.gz
    - python3 -u $CI_PROJECT_DIR/tests/ci_test.py --chip $TARGET_NAME --build $CI_PROJECT_DIR/build

.run_tests_v4.4:
  stage: test
  image: $CI_DOCKER_REGISTRY/esp32-ci-env:priv-sep
  tags:
    - test_esppool
  script:
    - tar -xzf ${CI_PIPELINE_ID}_${TARGET_NAME}_v4.4.tar.gz
    - python3 -u $CI_PROJECT_DIR/tests/ci_test.py --chip $TARGET_NAME --build $CI_PROJECT_DIR/build

esp32c3_run_tests_v4.3:
  extends: .run_tests_v4.3
  variables:
    TARGET_NAME: "esp32c3"

esp32c3_run_tests_v4.4:
  extends: .run_tests_v4.4
  variables:
    TARGET_NAME: "esp32c3"

esp32s3_run_tests_v4.4:
  extends: .run_tests_v4.4
  variables:
    TARGET_NAME: "esp32s3"

build_docs:
  stage: docs
  image: $CI_DOCKER_REGISTRY/esp-idf-doc-env:v4.4-1-v4
  tags:
    - docs
  artifacts:
    when: always
    paths:
      - docs/_build/*/*/*.txt
      - docs/_build/*/*/html/*
    expire_in: 4 days
  needs: []
  before_script: []
  after_script: []
  script:
    - python --version
    - cd docs
    - pip install -r requirements.txt
    - build-docs -t esp32c3 -l en

.deploy_docs_template:
  stage: docs
  image: $CI_DOCKER_REGISTRY/esp-idf-doc-env:v4.4-1-v4
  tags:
    - docs
  needs: ["build_docs"]
  before_script: []
  after_script: []
  script:
    - source ${CI_PROJECT_DIR}/docs/utils.sh
    - add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
    - export GIT_VER=$(git describe --always)
    - pip install -r ${CI_PROJECT_DIR}/docs/requirements.txt
    - deploy-docs

deploy_docs_preview:
  extends:
    - .deploy_docs_template
  except:
    refs:
      - master
  variables:
    TYPE: "preview"
    DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
    DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PREVIEW_DEPLOY_KEY"
    DOCS_DEPLOY_SERVER: "$DOCS_PREVIEW_SERVER"
    DOCS_DEPLOY_SERVER_USER: "$DOCS_PREVIEW_SERVER_USER"
    DOCS_DEPLOY_PATH: "$DOCS_PREVIEW_PATH"
    DOCS_DEPLOY_URL_BASE: "https://$DOCS_PREVIEW_SERVER_URL/docs/esp-privilege-separation"

deploy_docs_production:
  extends:
    - .deploy_docs_template
  only:
    refs:
      - master
  when: manual
  variables:
    TYPE: "production"
    DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
    DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PROD_DEPLOY_KEY"
    DOCS_DEPLOY_SERVER: "$DOCS_PROD_SERVER"
    DOCS_DEPLOY_SERVER_USER: "$DOCS_PROD_SERVER_USER"
    DOCS_DEPLOY_PATH: "$DOCS_PROD_PATH"
    DOCS_DEPLOY_URL_BASE: "https://docs.espressif.com/projects/esp-privilege-separation"
